# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='phone',
            new_name='telephone',
        ),
    ]
