# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180426_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_city', models.CharField(max_length=10, verbose_name='收货人城市')),
                ('receiver_telephone', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('receiver_address', models.CharField(max_length=150, verbose_name='收货地址')),
                ('receiver_name', models.CharField(max_length=10, verbose_name='收货人姓名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
