# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_receiveraddress_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to='account.ReceiverAddress'),
        ),
        migrations.AlterField(
            model_name='receiveraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
