# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180501_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='receiver',
            new_name='receiver_default',
        ),
    ]
