# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180501_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveraddress',
            name='is_default',
        ),
    ]
