# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_receiveraddress_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveraddress',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='状态'),
        ),
    ]
