# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='产地名')),
            ],
            options={
                'verbose_name_plural': '产地列表',
                'verbose_name': '商品产地',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品分类名')),
                ('status', models.SmallIntegerField(choices=[(0, '正常'), (1, '删除')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '种类列表',
                'verbose_name': '商品种类',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('images', models.ImageField(upload_to='goods/%Y/%m/%d', verbose_name='商品图片地址')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('click_count', models.IntegerField(default=0, verbose_name='商品点击量')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('status', models.SmallIntegerField(choices=[(0, '正常'), (1, '删除')], verbose_name='状态')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('stock', models.IntegerField(verbose_name='商品库存')),
                ('detail', tinymce.models.HTMLField(verbose_name='商品详情')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GoodsArea', verbose_name='商品产地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GoodsCategory', verbose_name='商品分类')),
            ],
            options={
                'verbose_name_plural': '商品列表',
                'verbose_name': '商品详情',
            },
        ),
    ]
