# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.GoodsArea', verbose_name='商品产地'),
        ),
    ]
