# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180501_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '删除')], default=0, verbose_name='状态'),
        ),
    ]
