# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_auto_20180501_0926'),
        ('account', '0011_userdetail_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_price', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='商品价格')),
                ('total', models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True, verbose_name='商品总价')),
                ('count', models.IntegerField(verbose_name='商品数量')),
                ('goods_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GoodsInfo', verbose_name='商品信息')),
            ],
            options={
                'verbose_name_plural': '订单详情',
                'verbose_name': '订单详情',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('sub_time', models.DateField(auto_now_add=True, verbose_name='提交时间')),
                ('pay_time', models.DateField(blank=True, null=True, verbose_name='付款时间')),
                ('status', models.SmallIntegerField(choices=[(-1, '取消'), (0, '创建'), (1, '未支付'), (2, '已支付'), (3, '未发货'), (4, '已发货')], default=0, verbose_name='订单状态')),
                ('total', models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='商品总价')),
                ('receiver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.ReceiverAddress', verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单中心',
                'verbose_name': '订单中心',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoporder.OrderMain', verbose_name='订单中心'),
        ),
    ]
