# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoporder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='商品总价'),
        ),
    ]
