# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoporder', '0002_auto_20180508_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='商品总价'),
        ),
    ]
