# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_auto_20180501_0926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_num', models.IntegerField(default=0, verbose_name='购买数量')),
                ('create_time', models.DateField(auto_now=True)),
                ('goodinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GoodsInfo', verbose_name='商品信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shopcart',
            unique_together=set([('goodinfo', 'user')]),
        ),
    ]
