# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0002_shopcart_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopcart',
            unique_together=set([]),
        ),
    ]
