# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180501_0926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopcart', '0003_auto_20180508_0643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopcart',
            unique_together=set([('goodinfo', 'user')]),
        ),
    ]
